# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x65tection.proto\x12\tdetection\"\x1d\n\x0c\x46rameRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"A\n\x04\x42\x42ox\x12\x0c\n\x04xmin\x18\x01 \x01(\x05\x12\x0c\n\x04ymin\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"\x99\x01\n\nObjectInfo\x12\x10\n\x08track_id\x18\x01 \x01(\x05\x12\x10\n\x08\x63lass_id\x18\x02 \x01(\x05\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x1d\n\x04\x62\x62ox\x18\x04 \x01(\x0b\x32\x0f.detection.BBox\x12\x10\n\x08\x64istance\x18\x05 \x01(\x02\x12\x10\n\x08\x63\x65nter_x\x18\x06 \x01(\x05\x12\x10\n\x08\x63\x65nter_y\x18\x07 \x01(\x05\"4\n\nObjectList\x12&\n\x07objects\x18\x01 \x03(\x0b\x32\x15.detection.ObjectInfo2L\n\x10\x44\x65tectionService\x12\x38\n\x06\x44\x65tect\x12\x17.detection.FrameRequest\x1a\x15.detection.ObjectListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=30
  _globals['_FRAMEREQUEST']._serialized_end=59
  _globals['_BBOX']._serialized_start=61
  _globals['_BBOX']._serialized_end=126
  _globals['_OBJECTINFO']._serialized_start=129
  _globals['_OBJECTINFO']._serialized_end=282
  _globals['_OBJECTLIST']._serialized_start=284
  _globals['_OBJECTLIST']._serialized_end=336
  _globals['_DETECTIONSERVICE']._serialized_start=338
  _globals['_DETECTIONSERVICE']._serialized_end=414
# @@protoc_insertion_point(module_scope)
