# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gRPC/distance.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gRPC/distance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gRPC/distance.proto\"\x1d\n\x0c\x46rameRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"8\n\x10\x45stimateResponse\x12\r\n\x05speed\x18\x01 \x01(\x02\x12\x15\n\rsafe_distance\x18\x02 \x01(\x02\x32?\n\x0f\x44istanceService\x12,\n\x08\x45stimate\x12\r.FrameRequest\x1a\x11.EstimateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPC.distance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=23
  _globals['_FRAMEREQUEST']._serialized_end=52
  _globals['_ESTIMATERESPONSE']._serialized_start=54
  _globals['_ESTIMATERESPONSE']._serialized_end=110
  _globals['_DISTANCESERVICE']._serialized_start=112
  _globals['_DISTANCESERVICE']._serialized_end=175
# @@protoc_insertion_point(module_scope)
